clusters:
  - name: main
    # only default versions
    # renovate: eksFilter={"default":true}
    version: 1.31 # next version must be 1.25
  - name: tier-1
    # region and where or not only default versions
    # renovate: eksFilter={"default":"false", "region":"eu-west-1"}
    version: 1.28 # next version must be 1.29
